stages:
  - deploy
deploy:
  stage: deploy
  image: python:latest
  only:
    - /^version.*$/
  services:
    - docker:dind
  before_script:
    - echo "$SSH_PRIVATE_KEY" > ssh_key
    - chmod 400 ssh_key
    - eval $(ssh-agent -s)
    - ssh-add ssh_key
    - rm ssh_key
  script:
    - apt-get update && apt-get install -y ansible
    - pip install docker
    - pip3 install docker
    - ansible-playbook -i hosts prometheus.yml -u root -e "alertmanager_web_password=$alertmanager_web_password prometheus_web_password=$prometheus_web_password rnd_consul_dev_token=$rnd_consul_dev_token rnd_consul_live_token=$rnd_consul_live_token rnd_consul_uat_token=$rnd_consul_uat_token rnd_vault_dev_token=$rnd_vault_dev_token rnd_vault_live_token=$rnd_vault_live_token"
