- name: Install and configure Prometheus
  hosts: FLT-Prometheus
  vars:
    ansible_python_interpreter: /usr/bin/python3
    my_become_var: true  # Renamed the variable to avoid using reserved keyword
  roles:
    - prometheus
