---
# handlers file for prometheus
- name: Reload Prometheus
  ansible.builtin.uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    headers:
      Authorization: "Basic {{ prometheus_basic_auth }}"
  changed_when: false

- name: Reload Alertmanager
  ansible.builtin.uri:
    url: "http://localhost:9093/-/reload"
    method: POST
    headers:
      Authorization: "Basic {{ alertmanager_basic_auth }}"
  changed_when: false
