---
# handlers file for prometheus
- name: Reload Prometheus
  ansible.builtin.uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    user: admin
    password: "{{ prometheus_web_password }}"
  changed_when: false

- name: Reload Alertmanager
  ansible.builtin.uri:
    url: "http://localhost:9093/-/reload"
    method: POST
    user: admin
    password: "{{ alertmanager_web_password }}"
  changed_when: false
