---
- name: Create a AlertManager templates directory
  file:
    path: /etc/prometheus/template
    state: directory
    mode: 0755
    owner: "1001"
    group: "1001"

- name: Copy Alertmanager alertmanager_web.yml files
  copy:
    src: prometheus/files/alertmanager_web.yml
    dest: /etc/prometheus/alertmanager_web.yml

- name: Copy AlertManager configuration
  copy:
    src: alertmanager.yaml
    dest: /etc/prometheus/alertmanager.yaml
    group: "1001"
    owner: "1001"
    mode: 0644
  notify: reload alertmanager

- name: Copy status alertmanager email template
  copy:
    src: email.tmpl
    dest: /etc/prometheus/email.tmpl

- name: Copy Yellow status alertmanager email template
  copy:
    src: email-yellow.tmpl
    dest: /etc/prometheus/email-yellow.tmpl

- name: Copy Orange status alertmanager email template
  copy:
    src: email-orange.tmpl
    dest: /etc/prometheus/email-orange.tmpl

- name: Copy RED status alertmanager email template
  copy:
    src: email-red.tmpl
    dest: /etc/prometheus/email-red.tmpl

- name: Copy Yellow EAMS status alertmanager email template
  copy:
    src: email-yellow-eams.tmpl
    dest: /etc/prometheus/email-yellow-eams.tmpl

- name: Copy Orange EAMS status alertmanager email template
  copy:
    src: email-orange-eams.tmpl
    dest: /etc/prometheus/email-orange-eams.tmpl

- name: Copy Red EAMS status alertmanager email template
  copy:
    src: email-red-eams.tmpl
    dest: /etc/prometheus/email-red-eams.tmpl

- name: Start AlertManager
  docker_container:
    name: alertmanager
    image: prom/alertmanager:v0.25.0
    networks:
      - name: fltechnics
    state: started
    restart_policy: always
    published_ports:
      - "9093:9093"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/prometheus/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
      - '--web.external-url=http://alertmanager.fltechnics.com'
      - '--web.config.file=/etc/alertmanager/alertmanager_web.yml'
