---
- name: Create a Prometheus configuration directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
    owner: "1001"
    group: "1001"

- name: Create a Prometheus data directory
  ansible.builtin.file:
    path: /home/prometheus-data
    state: directory
    mode: '0755'

- name: Copy Prometheus prometheus_web.yml files
  ansible.builtin.copy:
    src: prometheus/files/prometheus_web.yml
    dest: /etc/prometheus/prometheus_web.yml
    group: "1001"
    owner: "1001"
    mode: '0644'

- name: Copy certs
  ansible.builtin.copy:
    src: certs
    dest: /etc/prometheus/
    mode: '0755'
    group: "1001"
    owner: "1001"

- name: Copy Prometheus alerts/rules files
  ansible.builtin.copy:
    src: "{{ item }}"
    mode: '0644'
    owner: "1001"
    group: "1001"
    dest: "/etc/prometheus/{{ item }}"
    validate: "docker run -v %s:/tmp/{{ item }} dnanexus/promtool:2.9.2 check rules /tmp/{{ item }}"
  with_items:
    - base.alerts
    - windows.alerts
  notify: reload Prometheus

- name: Create a docker volume for prometheus with options
  community.docker.docker_volume:
    name: prometheus-data
    driver_options:
      type: block
      device: /home/prometheus-data
      o: bind

- name: Start Prometheus
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:v2.46.0
    networks:
      - name: fltechnics
    state: started
    restart_policy: always
    published_ports:
      - "9090:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.config.file=/etc/prometheus/prometheus_web.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention=1460h'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
      - '--query.max-concurrency=50'

- name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yaml
    mode: '0644'
    owner: "1001"
    group: "1001"
    validate: "docker run -v /etc/prometheus:/tmp -v %s:/tmp/prometheus.yaml dnanexus/promtool:2.9.2 check config /tmp/prometheus.yaml"
  notify: reload prometheus
